// <auto-generated />
namespace AlohaWebServiceMobile.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MapeoDePagosV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MapeoDePagosV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202211032220510_MapeoDePagosV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
