using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AlohaLibrary.Infraestrutura;
using AlohaLibrary.Modelos;
using AlohaLibrary.Interfaces;
using AlohaLibrary.Contexto;

namespace AlohaLibrary.Implementaciones
{
    public class SUBServicio : ServicioBaseALH<SUB>, ISUB
    {
        public SUBServicio(AplicacionBdContextoALH contexto) : base(contexto)
        {
        }

        public override List<SUB> GetAll()
        {
            List<SUB> subMnus = new List<SUB>();

            string query = "SELECT * FROM SUB";

            DataSet ds = new DataSet();
            EjecutarConsulta(query).Fill(ds, "SUB");
            DataTable tabla = ds.Tables["SUB"];

            foreach (DataRow item in tabla.Rows)
            {
                subMnus.Add(new SUB()
                {
                    ID = int.Parse(item["ID"].ToString()),
                    SHORTNAME = item["SHORTNAME"].ToString(),
                    LONGNAME = item["LONGNAME"].ToString(),
                    ITEM01 = int.Parse(item["ITEM01"].ToString()),
                    ITEM02 = int.Parse(item["ITEM02"].ToString()),
                    ITEM03 = int.Parse(item["ITEM03"].ToString()),
                    ITEM04 = int.Parse(item["ITEM04"].ToString()),
                    ITEM05 = int.Parse(item["ITEM05"].ToString()),
                    ITEM06 = int.Parse(item["ITEM06"].ToString()),
                    ITEM07 = int.Parse(item["ITEM07"].ToString()),
                    ITEM08 = int.Parse(item["ITEM08"].ToString()),
                    ITEM09 = int.Parse(item["ITEM09"].ToString()),
                    ITEM10 = int.Parse(item["ITEM10"].ToString()),
                    ITEM11 = int.Parse(item["ITEM11"].ToString()),
                    ITEM12 = int.Parse(item["ITEM12"].ToString()),
                    ITEM13 = int.Parse(item["ITEM13"].ToString()),
                    ITEM14 = int.Parse(item["ITEM14"].ToString()),
                    ITEM15 = int.Parse(item["ITEM15"].ToString()),
                    ITEM16 = int.Parse(item["ITEM16"].ToString()),
                    ITEM17 = int.Parse(item["ITEM17"].ToString()),
                    ITEM18 = int.Parse(item["ITEM18"].ToString()),
                    ITEM19 = int.Parse(item["ITEM19"].ToString()),
                    ITEM20 = int.Parse(item["ITEM20"].ToString()),
                    ITEM21 = int.Parse(item["ITEM21"].ToString()),
                    ITEM22 = int.Parse(item["ITEM22"].ToString()),
                    ITEM23 = int.Parse(item["ITEM23"].ToString()),
                    ITEM24 = int.Parse(item["ITEM24"].ToString()),
                    ITEM25 = int.Parse(item["ITEM25"].ToString()),
                    ITEM26 = int.Parse(item["ITEM26"].ToString()),
                    ITEM27 = int.Parse(item["ITEM27"].ToString()),
                    ITEM28 = int.Parse(item["ITEM28"].ToString()),
                    ITEM29 = int.Parse(item["ITEM29"].ToString()),
                    ITEM30 = int.Parse(item["ITEM30"].ToString()),
                    ITEM31 = int.Parse(item["ITEM31"].ToString()),
                    ITEM32 = int.Parse(item["ITEM32"].ToString()),
                    ITEM33 = int.Parse(item["ITEM33"].ToString()),
                    ITEM34 = int.Parse(item["ITEM34"].ToString()),
                    ITEM35 = int.Parse(item["ITEM35"].ToString()),
                    ITEM36 = int.Parse(item["ITEM36"].ToString()),
                    ITEM37 = int.Parse(item["ITEM37"].ToString()),
                    ITEM38 = int.Parse(item["ITEM38"].ToString()),
                    ITEM39 = int.Parse(item["ITEM39"].ToString()),
                    ITEM40 = int.Parse(item["ITEM40"].ToString()),
                    ITEM41 = int.Parse(item["ITEM41"].ToString()),
                    ITEM42 = int.Parse(item["ITEM42"].ToString()),
                    ITEM43 = int.Parse(item["ITEM43"].ToString()),
                    ITEM44 = int.Parse(item["ITEM44"].ToString()),
                    ITEM45 = int.Parse(item["ITEM45"].ToString()),
                    ITEM46 = int.Parse(item["ITEM46"].ToString()),
                    ITEM47 = int.Parse(item["ITEM47"].ToString()),
                    ITEM48 = int.Parse(item["ITEM48"].ToString()),

                    PRICE01 = double.Parse(item["PRICE01"].ToString()),
                    PRICE02 = double.Parse(item["PRICE02"].ToString()),
                    PRICE03 = double.Parse(item["PRICE03"].ToString()),
                    PRICE04 = double.Parse(item["PRICE04"].ToString()),
                    PRICE05 = double.Parse(item["PRICE05"].ToString()),
                    PRICE06 = double.Parse(item["PRICE06"].ToString()),
                    PRICE07 = double.Parse(item["PRICE07"].ToString()),
                    PRICE08 = double.Parse(item["PRICE08"].ToString()),
                    PRICE09 = double.Parse(item["PRICE09"].ToString()),
                    PRICE10 = double.Parse(item["PRICE10"].ToString()),
                    PRICE11 = double.Parse(item["PRICE11"].ToString()),
                    PRICE12 = double.Parse(item["PRICE12"].ToString()),
                    PRICE13 = double.Parse(item["PRICE13"].ToString()),
                    PRICE14 = double.Parse(item["PRICE14"].ToString()),
                    PRICE15 = double.Parse(item["PRICE15"].ToString()),
                    PRICE16 = double.Parse(item["PRICE16"].ToString()),
                    PRICE17 = double.Parse(item["PRICE17"].ToString()),
                    PRICE18 = double.Parse(item["PRICE18"].ToString()),
                    PRICE19 = double.Parse(item["PRICE19"].ToString()),
                    PRICE20 = double.Parse(item["PRICE20"].ToString()),
                    PRICE21 = double.Parse(item["PRICE21"].ToString()),
                    PRICE22 = double.Parse(item["PRICE22"].ToString()),
                    PRICE23 = double.Parse(item["PRICE23"].ToString()),
                    PRICE24 = double.Parse(item["PRICE24"].ToString()),
                    PRICE25 = double.Parse(item["PRICE25"].ToString()),
                    PRICE26 = double.Parse(item["PRICE26"].ToString()),
                    PRICE27 = double.Parse(item["PRICE27"].ToString()),
                    PRICE28 = double.Parse(item["PRICE28"].ToString()),
                    PRICE29 = double.Parse(item["PRICE29"].ToString()),
                    PRICE30 = double.Parse(item["PRICE30"].ToString()),
                    PRICE31 = double.Parse(item["PRICE31"].ToString()),
                    PRICE32 = double.Parse(item["PRICE32"].ToString()),
                    PRICE33 = double.Parse(item["PRICE33"].ToString()),
                    PRICE34 = double.Parse(item["PRICE34"].ToString()),
                    PRICE35 = double.Parse(item["PRICE35"].ToString()),
                    PRICE36 = double.Parse(item["PRICE36"].ToString()),
                    PRICE37 = double.Parse(item["PRICE37"].ToString()),
                    PRICE38 = double.Parse(item["PRICE38"].ToString()),
                    PRICE39 = double.Parse(item["PRICE39"].ToString()),
                    PRICE40 = double.Parse(item["PRICE40"].ToString()),
                    PRICE41 = double.Parse(item["PRICE41"].ToString()),
                    PRICE42 = double.Parse(item["PRICE42"].ToString()),
                    PRICE43 = double.Parse(item["PRICE43"].ToString()),
                    PRICE44 = double.Parse(item["PRICE44"].ToString()),
                    PRICE45 = double.Parse(item["PRICE45"].ToString()),
                    PRICE46 = double.Parse(item["PRICE46"].ToString()),
                    PRICE47 = double.Parse(item["PRICE47"].ToString()),
                    PRICE48 = double.Parse(item["PRICE48"].ToString()),

                    PRMETHOD01 = int.Parse(item["PRMETHOD01"].ToString()),
                    PRMETHOD02 = int.Parse(item["PRMETHOD02"].ToString()),
                    PRMETHOD03 = int.Parse(item["PRMETHOD03"].ToString()),
                    PRMETHOD04 = int.Parse(item["PRMETHOD04"].ToString()),
                    PRMETHOD05 = int.Parse(item["PRMETHOD05"].ToString()),
                    PRMETHOD06 = int.Parse(item["PRMETHOD06"].ToString()),
                    PRMETHOD07 = int.Parse(item["PRMETHOD07"].ToString()),
                    PRMETHOD08 = int.Parse(item["PRMETHOD08"].ToString()),
                    PRMETHOD09 = int.Parse(item["PRMETHOD09"].ToString()),
                    PRMETHOD10 = int.Parse(item["PRMETHOD10"].ToString()),
                    PRMETHOD11 = int.Parse(item["PRMETHOD11"].ToString()),
                    PRMETHOD12 = int.Parse(item["PRMETHOD12"].ToString()),
                    PRMETHOD13 = int.Parse(item["PRMETHOD13"].ToString()),
                    PRMETHOD14 = int.Parse(item["PRMETHOD14"].ToString()),
                    PRMETHOD15 = int.Parse(item["PRMETHOD15"].ToString()),
                    PRMETHOD16 = int.Parse(item["PRMETHOD16"].ToString()),
                    PRMETHOD17 = int.Parse(item["PRMETHOD17"].ToString()),
                    PRMETHOD18 = int.Parse(item["PRMETHOD18"].ToString()),
                    PRMETHOD19 = int.Parse(item["PRMETHOD19"].ToString()),
                    PRMETHOD20 = int.Parse(item["PRMETHOD20"].ToString()),
                    PRMETHOD21 = int.Parse(item["PRMETHOD21"].ToString()),
                    PRMETHOD22 = int.Parse(item["PRMETHOD22"].ToString()),
                    PRMETHOD23 = int.Parse(item["PRMETHOD23"].ToString()),
                    PRMETHOD24 = int.Parse(item["PRMETHOD24"].ToString()),
                    PRMETHOD25 = int.Parse(item["PRMETHOD25"].ToString()),
                    PRMETHOD26 = int.Parse(item["PRMETHOD26"].ToString()),
                    PRMETHOD27 = int.Parse(item["PRMETHOD27"].ToString()),
                    PRMETHOD28 = int.Parse(item["PRMETHOD28"].ToString()),
                    PRMETHOD29 = int.Parse(item["PRMETHOD29"].ToString()),
                    PRMETHOD30 = int.Parse(item["PRMETHOD30"].ToString()),
                    PRMETHOD31 = int.Parse(item["PRMETHOD31"].ToString()),
                    PRMETHOD32 = int.Parse(item["PRMETHOD32"].ToString()),
                    PRMETHOD33 = int.Parse(item["PRMETHOD33"].ToString()),
                    PRMETHOD34 = int.Parse(item["PRMETHOD34"].ToString()),
                    PRMETHOD35 = int.Parse(item["PRMETHOD35"].ToString()),
                    PRMETHOD36 = int.Parse(item["PRMETHOD36"].ToString()),
                    PRMETHOD37 = int.Parse(item["PRMETHOD37"].ToString()),
                    PRMETHOD38 = int.Parse(item["PRMETHOD38"].ToString()),
                    PRMETHOD39 = int.Parse(item["PRMETHOD39"].ToString()),
                    PRMETHOD40 = int.Parse(item["PRMETHOD40"].ToString()),
                    PRMETHOD41 = int.Parse(item["PRMETHOD41"].ToString()),
                    PRMETHOD42 = int.Parse(item["PRMETHOD42"].ToString()),
                    PRMETHOD43 = int.Parse(item["PRMETHOD43"].ToString()),
                    PRMETHOD44 = int.Parse(item["PRMETHOD44"].ToString()),
                    PRMETHOD45 = int.Parse(item["PRMETHOD45"].ToString()),
                    PRMETHOD46 = int.Parse(item["PRMETHOD46"].ToString()),
                    PRMETHOD47 = int.Parse(item["PRMETHOD47"].ToString()),
                    PRMETHOD48 = int.Parse(item["PRMETHOD48"].ToString()),
                    PRICELVL01 = int.Parse(item["PRICELVL01"].ToString()),
                    PRICELVL02 = int.Parse(item["PRICELVL02"].ToString()),
                    PRICELVL03 = int.Parse(item["PRICELVL03"].ToString()),
                    PRICELVL04 = int.Parse(item["PRICELVL04"].ToString()),
                    PRICELVL05 = int.Parse(item["PRICELVL05"].ToString()),
                    PRICELVL06 = int.Parse(item["PRICELVL06"].ToString()),
                    PRICELVL07 = int.Parse(item["PRICELVL07"].ToString()),
                    PRICELVL08 = int.Parse(item["PRICELVL08"].ToString()),
                    PRICELVL09 = int.Parse(item["PRICELVL09"].ToString()),
                    PRICELVL10 = int.Parse(item["PRICELVL10"].ToString()),
                    PRICELVL11 = int.Parse(item["PRICELVL11"].ToString()),
                    PRICELVL12 = int.Parse(item["PRICELVL12"].ToString()),
                    PRICELVL13 = int.Parse(item["PRICELVL13"].ToString()),
                    PRICELVL14 = int.Parse(item["PRICELVL14"].ToString()),
                    PRICELVL15 = int.Parse(item["PRICELVL15"].ToString()),
                    PRICELVL16 = int.Parse(item["PRICELVL16"].ToString()),
                    PRICELVL17 = int.Parse(item["PRICELVL17"].ToString()),
                    PRICELVL18 = int.Parse(item["PRICELVL18"].ToString()),
                    PRICELVL19 = int.Parse(item["PRICELVL19"].ToString()),
                    PRICELVL20 = int.Parse(item["PRICELVL20"].ToString()),
                    PRICELVL21 = int.Parse(item["PRICELVL21"].ToString()),
                    PRICELVL22 = int.Parse(item["PRICELVL22"].ToString()),
                    PRICELVL23 = int.Parse(item["PRICELVL23"].ToString()),
                    PRICELVL24 = int.Parse(item["PRICELVL24"].ToString()),
                    PRICELVL25 = int.Parse(item["PRICELVL25"].ToString()),
                    PRICELVL26 = int.Parse(item["PRICELVL26"].ToString()),
                    PRICELVL27 = int.Parse(item["PRICELVL27"].ToString()),
                    PRICELVL28 = int.Parse(item["PRICELVL28"].ToString()),
                    PRICELVL29 = int.Parse(item["PRICELVL29"].ToString()),
                    PRICELVL30 = int.Parse(item["PRICELVL30"].ToString()),
                    PRICELVL31 = int.Parse(item["PRICELVL31"].ToString()),
                    PRICELVL32 = int.Parse(item["PRICELVL32"].ToString()),
                    PRICELVL33 = int.Parse(item["PRICELVL33"].ToString()),
                    PRICELVL34 = int.Parse(item["PRICELVL34"].ToString()),
                    PRICELVL35 = int.Parse(item["PRICELVL35"].ToString()),
                    PRICELVL36 = int.Parse(item["PRICELVL36"].ToString()),
                    PRICELVL37 = int.Parse(item["PRICELVL37"].ToString()),
                    PRICELVL38 = int.Parse(item["PRICELVL38"].ToString()),
                    PRICELVL39 = int.Parse(item["PRICELVL39"].ToString()),
                    PRICELVL40 = int.Parse(item["PRICELVL40"].ToString()),
                    PRICELVL41 = int.Parse(item["PRICELVL41"].ToString()),
                    PRICELVL42 = int.Parse(item["PRICELVL42"].ToString()),
                    PRICELVL43 = int.Parse(item["PRICELVL43"].ToString()),
                    PRICELVL44 = int.Parse(item["PRICELVL44"].ToString()),
                    PRICELVL45 = int.Parse(item["PRICELVL45"].ToString()),
                    PRICELVL46 = int.Parse(item["PRICELVL46"].ToString()),
                    PRICELVL47 = int.Parse(item["PRICELVL47"].ToString()),
                    PRICELVL48 = int.Parse(item["PRICELVL48"].ToString()),

                    //PANELES, SI EL VALOR AQUI ES DIFERENTE A CERO SIGNIFICA QUE SE USAN PANELES

                    PANEL_ID = int.Parse(item["PANEL_ID"].ToString()),
                });
            }

            return subMnus;
        }
    }
}
